[build-system]
requires = ["setuptools>=68"]         # Supports PEP 660 editable installs
build-backend = "setuptools.build_meta"

[project]
name = "automated-research-report-generation"
version = "0.1.0"
description = "Automated Research and Report Generation System (ARRGS): A multi-agent LLMOps framework for AI-driven research, analysis, and report creation."
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "ipykernel>=6.30.1",
    "langchain-community>=0.3.30",
    "langchain-core>=0.3.78",
    "langchain-google-genai==2.1.8",
    "langchain-groq==0.3.6",
    "langchain-openai==0.3.32",
    "langgraph>=0.6.8",
    "structlog==25.4.0",
    "tavily-python>=0.7.12",
    "wikipedia>=1.4.0",
]

authors = [{ name = "Dr. Erick K. Yegon", email = "erickkiprotichyegon61@gmail.com" }]
license = { text = "Proprietary" }

[tool.setuptools.packages.find]
where = ["research_and_analyst"]
